fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: check-merge-conflict
  - id: check-ast
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      args: [ "--select", "F401", "--fix" ]
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
    args: ['--line-length', '119']
- repo: local
  hooks:
  - id: wtf
    name: WTF
    entry: '\b(?i:wtf)\b'
    types: [ python ]
    language: pygrep
  - id: pytest
    name: pytest
    entry: ./pathed-pylintest pytest
    always_run: true
    language: system
    pass_filenames: false
