#!/usr/bin/env python
# coding: utf-8

import inspect
import pandas as pd

import pdc
import pdc.util
import pdc.parser
import pdc.op

pdc.util.set_say_level(pdc.util.SAY_INFO)

from t.conftest import *
def unwrap_fixtures():
    g = globals()
    for name in g:
        try:
            item = g[name].__pytest_wrapped__.obj()
            g[name] = next(item) if inspect.isgenerator(item) else item
        except AttributeError:
            pass
/unwrap_fixtures
