#!/usr/bin/env python
# coding: utf-8

import pandas as pd

import pdc.util
import pdc.parser
import pdc.op

pdc.util.set_say_level(pdc.util.SAY_ERROR)

f1 = pdc.util.read_csv('t/asset/test1.csv')
f2 = pdc.util.read_csv('t/asset/test2.csv')
f3 = pdc.util.read_csv('t/asset/test3.csv')

def p(words, files=(f1,f2,f3)):
    return pdc.parser.parse(words, files=files)
