#!/usr/bin/env python

from pandas_cli.cmd import main

# NOTE: this is just a way to invoke the program in testing. The actual
# entrypoints are defined in setup.cfg

if __name__ == '__main__':
    main()
